[build]
# No target specified means Cargo uses your host’s default

# Linux
[target.x86_64-unknown-linux-gnu]

# Static linux
[target.x86_64-unknown-linux-musl]

# Windows
[target.x86_64-pc-windows-msvc]

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"

# Intel MacOS
[target.x86_64-apple-darwin]

# Apple Silicon MacOS
[target.aarch64-apple-darwin]

# iOS
[target.aarch64-apple-ios]

# Android
[target.aarch64-linux-android]

# Android x86_64 simulator
[target.x86_64-linux-android]

# Raspberry Pi
[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

# Raspberry Pi 32-bit
[target.armv7-unknown-linux-gnueabihf]
