[build]
# No target specified means Cargo uses your host’s default

## Linux
#[target.x86_64-unknown-linux-gnu]
#linker = "./.cargo/zig-cc"
#rustflags = ["-C", "link-arg=-fuse-ld=lld"]
#
## Static linux
#[target.x86_64-unknown-linux-musl]
#linker = "./.cargo/zig-cc"
#rustflags = ["-C", "link-arg=-fuse-ld=lld"]
#
## Windows
#[target.x86_64-pc-windows-msvc]
#linker = "./.cargo/zig-cc"
#
#[target.x86_64-pc-windows-gnu]
#linker = "./.cargo/zig-cc"

## Intel MacOS
#[target.x86_64-apple-darwin]
#linker = "./.cargo/zig-cc"

## Apple Silicon MacOS
#[target.aarch64-apple-darwin]
#linker = "./.cargo/zig-cc"

## iOS
#[target.aarch64-apple-ios]
#linker = "./.cargo/zig-cc"

## Android
#[target.aarch64-linux-android]
#linker = "./.cargo/zig-cc"

## Android x86_64 simulator
#[target.x86_64-linux-android]
#linker = "./.cargo/zig-cc"
#
## Raspberry Pi
#[target.aarch64-unknown-linux-gnu]
#linker = "./.cargo/zig-cc"
#
## Raspberry Pi 32-bit
#[target.armv7-unknown-linux-gnueabihf]
#linker = "./.cargo/zig-cc"
